name: medi_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=3.0.1 <4.0.0"
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  sms_autofill: ^2.3.0
  flutter_svg_provider: ^1.0.6
  intl: ^0.18.1
  country_code_picker: ^3.0.0

  pinput: ^3.0.1
  getwidget: ^4.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: SF Pro Display
      fonts: 
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplaySemibold.ttf
          weight: 600
    - family: Mona-Sans
      fonts: 
        - asset: assets/fonts/MonaSansBold.ttf
          weight: 700
        - asset: assets/fonts/MonaSansMedium.ttf
          weight: 500

    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lora-Semibold.ttf
          weight: 600
