import 'controller/add_new_card_active_controller.dart';import 'package:flutter/material.dart';import 'package:medi_app/core/app_export.dart';import 'package:medi_app/widgets/app_bar/appbar_image.dart';import 'package:medi_app/widgets/app_bar/appbar_title.dart';import 'package:medi_app/widgets/app_bar/custom_app_bar.dart';import 'package:medi_app/widgets/custom_elevated_button.dart';import 'package:medi_app/widgets/custom_text_form_field.dart';class AddNewCardActiveScreen extends GetWidget<AddNewCardActiveController> {const AddNewCardActiveScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [Container(padding: EdgeInsets.symmetric(vertical: 20.v), decoration: AppDecoration.outlineGray100, child: CustomAppBar(leadingWidth: 44.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleft, margin: EdgeInsets.only(left: 20.h, top: 1.v, bottom: 3.v), onTap: () {onTapArrowleftone();}), centerTitle: true, title: AppbarTitle(text: "lbl_add_new_card".tr))), Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v), child: Column(children: [Container(width: 364.h, margin: EdgeInsets.symmetric(horizontal: 15.h), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_enter_your_card2".tr, style: theme.textTheme.bodyLarge), TextSpan(text: "lbl_learn_more".tr, style: CustomTextStyles.bodyLargePrimary)]), textAlign: TextAlign.center)), SizedBox(height: 15.v), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_card_number".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 6.v), CustomTextFormField(controller: controller.cardNumberController, hintText: "lbl_1234_5874_1451".tr)]), SizedBox(height: 18.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 1.v, right: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_expiry_date".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 5.v), CustomTextFormField(width: 190.h, controller: controller.expirydateController, hintText: "lbl_08_28".tr, contentPadding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 17.v))]))), Expanded(child: Padding(padding: EdgeInsets.only(left: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_cvv".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 6.v), CustomTextFormField(width: 190.h, controller: controller.cvvController, hintText: "lbl_488".tr, textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 17.v))])))]), SizedBox(height: 30.v), CustomElevatedButton(text: "lbl_add_new_card".tr, onTap: () {onTapAddnewcard();}), SizedBox(height: 5.v)]))])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
/// Navigates to the myCardsScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the myCardsScreen.
onTapAddnewcard() { Get.toNamed(AppRoutes.myCardsScreen, ); } 
 }
