import '../onboarding2_screen/widgets/medicalappointm_item_widget.dart';import 'controller/onboarding2_controller.dart';import 'models/medicalappointm_item_model.dart';import 'package:carousel_slider/carousel_slider.dart';import 'package:flutter/material.dart';import 'package:medi_app/core/app_export.dart';import 'package:medi_app/widgets/custom_elevated_button.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';class Onboarding2Screen extends GetWidget<Onboarding2Controller> {const Onboarding2Screen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.lightBlue5002, body: SizedBox(width: double.maxFinite, child: Column(children: [CustomImageView(imagePath: ImageConstant.imgRectangle54581, height: 500.v, width: 428.h), Padding(padding: EdgeInsets.only(left: 33.h, top: 41.v, right: 33.h), child: Obx(() => CarouselSlider.builder(options: CarouselOptions(height: 140.v, initialPage: 0, autoPlay: true, viewportFraction: 1.0, enableInfiniteScroll: false, scrollDirection: Axis.horizontal, onPageChanged: (index, reason) {controller.sliderIndex.value = index;}), itemCount: controller.onboarding2ModelObj.value.medicalappointmItemList.value.length, itemBuilder: (context, index, realIndex) {MedicalappointmItemModel model = controller.onboarding2ModelObj.value.medicalappointmItemList.value[index]; return MedicalappointmItemWidget(model);}))), SizedBox(height: 21.v), Obx(() => SizedBox(height: 7.v, child: AnimatedSmoothIndicator(activeIndex: controller.sliderIndex.value, count: controller.onboarding2ModelObj.value.medicalappointmItemList.value.length, axisDirection: Axis.horizontal, effect: ScrollingDotsEffect(spacing: 6, activeDotColor: theme.colorScheme.primary, dotColor: theme.colorScheme.primary.withOpacity(0.46), dotHeight: 7.v, dotWidth: 7.h)))), CustomElevatedButton(text: "lbl_get_started".tr, margin: EdgeInsets.fromLTRB(16.h, 32.v, 16.h, 5.v), onTap: () {onTapGetstarted();})])))); } 
/// Navigates to the onboarding1Screen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the onboarding1Screen.
onTapGetstarted() { Get.toNamed(AppRoutes.onboarding1Screen, ); } 
 }
